smokerData <- read.csv(file='smoker.csv',header=T)
smoke <- table(smokerData$Smoke,smokerData$SES)
smoke2=addmargins(smoke)
smokeprob=prop.table(smoke)
smokeprob=addmargins(smokeprob)
sink("smoke-out.txt",split=2) 
cat("=======================\n")
cat("Summary data of smokers\n")
cat("=======================\n")
print(smoke2)
cat("=========================================\n")
cat("Joint probability distribution of smokers\n")
cat("=========================================\n")
print(smokeprob,digits=3)
cat("======================================\n")
cat("Percentage of smokers in each category\n")
cat("======================================\n")
print(smokeprob*100,digits=3)
sink()

